version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "demo/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "demo/app/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "crypto-checker-qual/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "crypto-checker-qual-android/"
    schedule:
      interval: "daily"
